### ISSUE TITLE
crash in 1.4.0 when requesting an item via the terminal

### ISSUE THREAD

**Issue by erisdev** [Ellpeck/PrettyPipes#10]
[crash-2020-05-09_03.40.25-server.txt](https://github.com/Ellpeck/PrettyPipes/files/4602940/crash-2020-05-09_03.40.25-server.txt)

the setup is barebones: a pipe connecting a chest to the terminal. the game crashes a moment after clicking the request button.

**Comment by Ellpeck** [comment]
This is due to only a single pipe existing in the network. Until this is fixed, you can just connect two pipes between the terminal and the chest instead of one and it'll work fine :)
