### ISSUE TITLE
Blocks placed as covers consumed in creative mode

### ISSUE THREAD

**Issue by MacyMacerator** [Ellpeck/PrettyPipes#100]
Blocks placed as covers on pipes are consumed in creative mode.
Block covers drop when the pipe is broken in creative mode.

Inconsistent with vanilla behavior for similar actions, but not definitely not game-breaking.
(nor does it look like something that broke with the version change, so.. sorry)

**Comment by Ellpeck** [comment]
I think this makes sense, because I think of the covers more as items placed into the pipe's inventory than... placing blocks? So I think I want this to stay this way. Any reasoning otherwise is welcome, though!
