### ISSUE TITLE
[Question] Item Terminal and Retrieval Modules

### ISSUE THREAD

**Issue by IdrisQe** [Ellpeck/PrettyPipes#106]
So we're playing the Create Above and Beyond Modpack and this pipe mod is included.

we're having a strange issue now that we're trying to automate a farm though- We have an inventory (a barrel) connected to a kelp farm, which then is connected via pipes to our storage system (a network of Storage Drawers from the mod of the same name connected to an Item Terminal via pipes) and I just put a Low Retrieval Module into the pipe adjacent to the Kelp pipe, except now it seems that I can't pull kelp from that pipe? Does having a retrieval module in the pipe beside a storage stop you from actually pulling items from it using an Item Terminal or something? The actual descriptions of the items don't make it clear at all, and I can't tell if this is intended functionality or a really crummy bug.

**Comment by Ellpeck** [comment]
A retrieval module extracts items from the storage network into a single destination container, so the destination container stops being considered a part of the network. An item terminal can only see containers that are a part of the network.
