### ISSUE TITLE
Terminals do not recognize Pneumaticcraft items that have air

### ISSUE THREAD

**Issue by chantrykomori** [Ellpeck/PrettyPipes#108]
This is more of a compatibility issue, but if a Pneumaticcraft item has air pressure, the terminals do not recognize them.

**Comment by Ellpeck** [comment]
What do you mean by "recognize"? Are they not displayed in the terminal at all?

**Comment by chantrykomori** [comment]
Sorry, I should be more clear. If an item has any air stored inside of it, it can't be pulled out by the item terminal. It's visible in the terminal like any item, but when you try to extract it the terminal tells you the item can't be found. This is consistent across all Pneumaticcraft items that can store air.
