### ISSUE TITLE
High Retrieval Module

### ISSUE THREAD

**Issue by mouse0270** [Ellpeck/PrettyPipes#11]
Alright, so I am having some wonky behavior with this module (which sucks because were playing pure survivor world and it took forever to farm up 20 of these modules).

But essential what is happening is I have an XP farm that uses 4 Zero Tick farms (2 for Bamboo and 2 for Cactus). These items are then ported into a Chest (Drawer from Storage Drawers) because these module apparently don't like pulling items out of a hopper, so we added a Drawers to the hoppers. Then we pipe the materials to 10 Furnaces with bamboo and cactus going to their correct spots. This is where we are having a weird problem.

Two of the furnaces wont retrieve any bamboo even though they can pull from a source of about 5k and one of them wont retrieve any cactus any though it's connected to a Drawer holding about 20k. But the other 7 furnaces are working just fine.

Looking at the server and client logs, I am not see anything... I am just confused why 3 of the furnaces would be acting in this manner. It's also weird that they will receive one of the items and not the other.

**Comment by Ellpeck** [comment]
Could it be that the furnaces are operating so fast (you didn't say whether you use modded furnaces) that the module isn't fast enough to insert into the remaining furnaces?
If you could send some screenshots, that'd help debug this problem.

**Comment by mouse0270** [comment]
I will add some screenshots... 2 of them are actually being passed, only one of the end one's are not receiving items. That is what makes it so weird.

**Comment by Ellpeck** [comment]
Are you certain that all of your retrieval modules are configured with a filter that tells them which items to pull?

**Comment by mouse0270** [comment]
Wait, I need a filter and a retrieval? I thought on retrieval you just drop the item into the little boxes and it will only retrieve that item?

**Comment by Ellpeck** [comment]
No, the retrieval modules need a their filter slots to be configured. A retrieval module with no items in its filter slots will *not* pull everything.

**Comment by mouse0270** [comment]
Yes, I started by filling all slots with their correct type, for example, the fuel part has bamboo in all slots and other one has cactus in all of its slots.

For the ones not working, I've tried only doing the first slow. I've also tried using the low and Medium tiers, but for some reason, these 3 furnaces still wont fill up with anything

The following screenshots are the ones with issues.
![image](https://user-images.githubusercontent.com/564874/81482914-62035280-9208-11ea-9abd-6d94e063cfb8.png)
![image](https://user-images.githubusercontent.com/564874/81482919-662f7000-9208-11ea-95d9-0be7f9b4376a.png)
![image](https://user-images.githubusercontent.com/564874/81482931-721b3200-9208-11ea-8f4f-284083b9d307.png)
![image](https://user-images.githubusercontent.com/564874/81482948-852e0200-9208-11ea-8efa-a8b6349a9ea6.png)
![image](https://user-images.githubusercontent.com/564874/81482958-95de7800-9208-11ea-8729-7313f7803a41.png)

Here is the configuration of all of the working ones
![image](https://user-images.githubusercontent.com/564874/81482967-b4447380-9208-11ea-8e15-6fb2751e23a5.png)
![image](https://user-images.githubusercontent.com/564874/81482973-c0303580-9208-11ea-9a16-be3f3414136a.png)

**Comment by Ellpeck** [comment]
A high retrieval module will only pull items if the maximum number it can pull (64) fits into the furnace. Are the furnaces that the items aren't going into completely empty?

**Comment by mouse0270** [comment]
To be fair, 85% of it working perfectly is fine, as this server is for a small group of friends... I just thought it was weird that they were all configured the same but not working the same.

**Comment by mouse0270** [comment]
> A high retrieval module will only pull items if the maximum number it can pull (64) fits into the furnace. Are the furnaces that the items aren't going into completely empty?

Yes, I thought that was the issue too, so I pulled everything out of the furnace. Though that doesn't seem to be correct. As all of the others are periodically getting items and none of them are empty. The ones not working are empty.

I even added items in hope that would "kickstart" the mod and make it try to pull more to keep it filled.

**Comment by Ellpeck** [comment]
Have you tried breaking the pipes and replacing them? This might be some sort of weird caching issue.
I just recreated the exact setup you have in a test world, and everything works fine for me. Meh.

**Comment by mouse0270** [comment]
That was the issue. Broke the pipes and reset them up and it seems to be all working fine...

I tried all of these more complicated issues, just needed to break and reset. lol

**Comment by Ellpeck** [comment]
If this issue comes back up, please reopen this issue (or open a new one). If it is in fact an issue with caching and saving/loading the chunks a few times breaks the setup, this obviously will have to be fixed.

If this was just a one-off, then I don't think there's much I can do.
