### ISSUE TITLE
Terminal right click behavior

### ISSUE THREAD

**Issue by HancockC43** [Ellpeck/PrettyPipes#113]
Version: 1.9.5
Forge: 36.2.20
Minecraft: 1.16.5

Right clicking the search bar in the item or crafting terminal does not select the search bar. The input line appears and blinks in the search bar, but typing does not input text.

expected behavior: right click clears the search bar and selects the field so text can be input without also having to left click. This would be the same behavior as JEI and other storage mods (Refined storage, AE2)

**Comment by Ellpeck** [comment]
This issue was resolved by #114.
