### ISSUE TITLE
[Bug] Search Bar selection and activation

### ISSUE THREAD

**Issue by Ridanisaurus** [Ellpeck/PrettyPipes#123]
When using Pretty Pipes terminal, and you have something in the search bar, you can right/left click it (don't remember which) to clear it, and it shows you that you are ready to type your next search criteria, but if you type, it doesn't actually search. You have to click again on the search bar before typing.
Version: PrettyPipes-1.9.6

**Comment by Nagapito** [comment]
Would it be possible to have just one last 1.16 version released where this issue is fixed?

1.16 version is pretty good except this issue that is the most annoying thing and makes people get really frustrated with the mod...

Thanks
