### ISSUE TITLE
[Request] Configurable pipe speed 

### ISSUE THREAD

**Issue by Jerome226** [Ellpeck/PrettyPipes#124]
Basically this suggestion is to add a way to configure the base speed of pipes and change the modifier of upgrades/pressurizer.
Would allows to make some upgrades maybe less powerful, some a bit more.
Could also be added for other upgrades like export/crafting to configure other of their properties.

**Comment by Ellpeck** [comment]
I'm not really interested in adding a feature like this right now. Sorry!
