### ISSUE TITLE
[suggestion] more convenient tag filtering

### ISSUE THREAD

**Issue by smoluwu** [Ellpeck/PrettyPipes#129]
i feel like the 3 modules per pipe thing is okay, but it gets quite limiting if you want to have a chest filtered by more tags than one since a priority module + a filter module + a tag module takes all three of those slots and only allows you to filter one tag. i think it would be good if the filter modifiers could be inserted into the filter itself per slot or something, or maybe allowing multiple tags to be picked from the filter the higher the teir the filter is

**Comment by Ellpeck** [comment]
Sorry, but I'm not really interested in expanding the functionality of the tag filter modifier. 

I talked about this a lot in various places, including on this issue tracker, but I'm not a big fan of the tag filter modifier to begin with, and I think filtering by a set of items is always a better solution. Tags are an engine-internal feature that I don't think should be exposed to players (similarly to chunks) and I only very begrudgingly added the tag filter modifier in the first place.
