### ISSUE TITLE
Requesting ingredients when some are missing doesn't work on linux

### ISSUE THREAD

**Issue by nddragoon** [Ellpeck/PrettyPipes#130]
When a recipe is missing stuff in the system, the chat prompts you to alt-click to request the rest anyway, but this doesn't work on most linux desktops as alt can be used to drag windows around. Would be good to get a way to change the keybind, or if not possible at least change the default to something like space.

**Comment by Ellpeck** [comment]
I- what. There are so many things that use Alt as a modifier key. How do people on Linux get by. That is so stupid.

I guess I'll change it to something else then, yea.
