### ISSUE TITLE
Auto crafting recipe to produce 100% durability Immersive Engineer Graphite Electrodes causes server crash

### ISSUE THREAD

**Issue by Sparklingtips** [Ellpeck/PrettyPipes#132]
This crash was experienced playing Enigmatica 6 Expert. This one is a bit weird to explain but basically the pretty pipes recipe that seems to be causing the server crash is that when you have a recipe that creates an Immersive Engineering Electrode using the Metal Press (which are created at 50% durability) and then another recipe that tries to craft them together to make a 100% durability electrode something in compareItems causes a crash with the recipe to combine the electrodes.

Crash Report: https://mcpaste.io/4084a159305f47a2

Recipe in question: https://gyazo.com/2f4bf352b5cbe4275ec0fc90b80ec57d

**Comment by Ellpeck** [comment]
Hi! It would be great if you could try to reproduce this issue with [this version](https://ci.ellpeck.de/job/PrettyPipes/job/main/77/artifact/build/libs/PrettyPipes-1.12.2.77.jar). It might be fixed, but it might also have gotten worse.
