### ISSUE TITLE
E6E trying output fluid in regular pipe insta crash server

### ISSUE THREAD

**Issue by Gayanfalor** [Ellpeck/PrettyPipes#135]
Hello, i was playing Enigmatica 6 expert modpack and wanted to output ridge runner honey into a tank linked out from the centrifuge, there is a diamond chest next to the tank i placed.

I didnt know there was fluid pipes so i used regular pipes with some  pipe addons extraction from the centrifuge, fluid retriever on the tank pipe, and then after a bit the server crash

pretty pipe ver 1.9.8
pretty pipe fluid 0.4.1

[crash-2022-06-08_21.23.41-server.txt](https://github.com/Ellpeck/PrettyPipes/files/8867601/crash-2022-06-08_21.23.41-server.txt)

**Comment by Ellpeck** [comment]
This is an issue with Pretty Fluid Pipes.

**Comment by Gayanfalor** [comment]
huh ? even if in my setup there is no fluid pipe only regular pipe from pretty pipes ? so i should post issue on their mod then ?

thanks
