### ISSUE TITLE
Can't use filters on pipes anymore.

### ISSUE THREAD

**Issue by beouwolfe** [Ellpeck/PrettyPipes#14]
I have not added, changed, or updated any modes in a week but starting yesterday in my single player world, I can no longer right click on pipes with a filter to open the window.

Existing filters in pipes continue to work as set up. I can add filters to pipes in a new world. I just can no longer add filters to my existing world.

 Do you know of something I can do to fix this?

**Comment by Ellpeck** [comment]
You can only insert filters into pipes that are connected to inventories, but I assume that's what you're trying to do.

**Comment by Ellpeck** [comment]
Wait, I'm pretty sure I made it so that you can only open the pipe gui with an empty hand. 🤔
