### ISSUE TITLE
Crash with High Retrival from Pretty Pipes

### ISSUE THREAD

**Issue by rgdelta1973** [Ellpeck/PrettyPipes#145]
I tried setting up a Steel and Enderium generators from iron generators with automatic Charcoal from my Pretty Pipes/Storage Drawers storage system. I put Speed and High retrieval from pretty pipes in each end with charcoal as the retrevial item. Then my world crashed after I connected it to the network and game would continue to crash when trying to load the world.

Then after I got my last backup I decided to setup a Storage Drawer with the single stack downgrade and have pretty pipes fill it up from my main system then use Pipez Item pipes to pipe the charcoal in from the drawer to the generators after I setup the drawer put a pretty pipe (not connected to the network) and put in the speed and high retrieval upgrade with charcoal filter as soon as I closed the interface and put the charcoal I had in the my inventory had the crash again

Same issue as the first the world would crash the game on load (need to go back from the backup). Not sure if this is a modpack issue or issue with pretty pipes but posting it here first. I do have the pipe pressurizer on the network (but 2nd time the pipe was not hooked up to the network)

I am using TNP Limitless 5 version 2.14 which has Pretty Pipes Version 1.12.5 (1.18.2 Modpack)
I reported to Mod Pack Maker as well and he suggested also posting here

Will include Crash logs on pastebin links

First Crash Log https://pastebin.com/x9HffvTB
Second Crash Log https://pastebin.com/7ugC4TUW

**Comment by Ellpeck** [comment]
Please update Pretty Pipes to 1.12.6.
