### ISSUE TITLE
Routing fluids ignore priority modules

### ISSUE THREAD

**Issue by Porcy** [Ellpeck/PrettyPipes#150]
Details here:
https://www.reddit.com/r/feedthebeast/comments/x5ybsb/why_is_my_etching_acid_being_deleted/?%24deep_link=true&correlation_id=b460b345-287f-406d-ada2-a54eb8e29149&ref=email_post_reply&ref_campaign=email_post_reply&ref_source=email&%243p=e_as&_branch_match_id=918256514748455129&utm_medium=Email%20Amazon%20SES&_branch_referrer=H4sIAAAAAAAAA3VOW2rEMAw8TfqXZGs76W5hKYXSawjZVhKzjm1shTS3r0Pbz4IEo3kwWphTee37TNY67jClzrvw6GV6a4SS6U6A5anCmN3sAnrYsr8vZ6qR7434rLPve%2FebN3GtRK47EVleSBMWrmcVVgpcKvwaDl30mVsOcAXWA4jN4sIMaJwFTSe05InJng2ylihLlOB8rZEfnDdqxGhizuSRXQzgbOW1Gi9aqqEV15epVZfRtmhRtDgo0lcSt2d1q7lMUzXTis5DioUhU%2FLHjwAG14RuDv87StyyoT%2F9GyHF3NhBAQAA

**Comment by Ellpeck** [comment]
Pretty Pipes doesn't support fluids. You're probably using the Pretty Fluid Pipes addon.
