### ISSUE TITLE
Is it possible to request a full stack with a single click?

### ISSUE THREAD

**Issue by jvillal84** [Ellpeck/PrettyPipes#151]
Hi! First of all, congrats for the great mod!

I'm using Pretty Pipes 1.12.6 on Minecraft 1.18.2. I just made a crafting terminal and it is neat!

Every time I need to take a high amount of a given material (let's say a whole stack of iron) it is a bit tedious to click the '+' button (or hit space key) 64 times. Is there any shortcut to do that on a single click? (as it is done with a regular chest).

Thanks in advance!

**Comment by Ellpeck** [comment]
You can hold Shift, Alt and Control to request different amounts!

**Comment by jvillal84** [comment]
Thanks a lot! I didn't thought of holding Shift or Alt when clicking the "+" button. It works like charm! Thanks again :)
