### ISSUE TITLE
Filter modules keep disappearing after i log back in to my server, and the modules keep erasing the config

### ISSUE THREAD

**Issue by Hegoland** [Ellpeck/PrettyPipes#153]
I have a storage all connected with pipes and each one of them has a filter module, y config the whitelist and test the system and it works just fine, but when i log off and back in some of the modules keep going back to the red "D" of disallowed and some of the modules keep disappearing, its always the same ones and the other stuff i do in the server of each session saves perfectly. Does the system has limit of modules? Thanks for the help

**Comment by Ellpeck** [comment]
Hi, please try to reproduce this issue with just Pretty Pipes installed, and in a fresh world. If you can't reproduce it at all there, please try to figure out what mod might be causing the issue, or whether there is some sort of chunk/region corruption in your world that may cause configurations to be reset. Thanks!

**Comment by Hegoland** [comment]
Ok thanks

**Comment by Hegoland** [comment]
UPDATE: I was able to replicate the error like asked, in large networks this randomly happens, the way i was able to solve this in my server (wich has 300 chests in the network) was to remove all the pipes that were having issues and the trying to put them back and attatch the module. This was working sometimes and sometimes it would dissapear again, the way i found consistent was putting them 2 by 2. I put 2 pipes into 2 chests, put the module in and change to whitelist and then log put and back in, i had to do this for like 100 chests

**Comment by Ellpeck** [comment]
Hmm. Can you share the log file from a session that this happened in? Maybe there is some information in it about something being unable to save.

**Comment by Hegoland** [comment]
How can i get that? Today the modules were fine but the item inside (the filter) keep disappearing if i do more than 5-6 at a time

**Comment by Israelkrdenas** [comment]
I have a similtar error in my own save, not a server save. What I need to change to solucionate that?

**Comment by Ellpeck** [comment]
Please share the full log file from a session that this happened it. There might be some information in it about the pipes being unable to save their data properly. Thanks!

**Comment by Israelkrdenas** [comment]
How I take the log file from a not server save?

**Comment by Ellpeck** [comment]
You can find the log file in your Minecraft instance's `logs` folder. The latest log file should be the one with the most up-to-date information in it, though it has to be from a session where this issue happened. If you don't know where your instance is stored, you can use the `Open Resource Pack Folder` button in the game's menu.

**Comment by Israelkrdenas** [comment]
Here you have my latest log. Thank you and I'm sorry for the inconvenience!

[latest.log](https://github.com/Ellpeck/PrettyPipes/files/9709845/latest.log)
