### ISSUE TITLE
Items being flung into world

### ISSUE THREAD

**Issue by clarketronics** [Ellpeck/PrettyPipes#156]
Once an item enters the pipe and travels to the receiver if that is full it will then travel back to where it came from. If that inventory is full it the items seem to "pop out" of the pipe this causes massive lag on servers with potentially 1000s of items on the ground.
![unknown-13](https://user-images.githubusercontent.com/38007037/193455268-c77bdd42-24ba-4fd7-a804-a67506183372.png)

**Comment by Ellpeck** [comment]
This is intended behavior. You should use higher tier extraction/retrieval modules, which prevent over-sending, causing no additional items to be sent once the container is thought to be full with all of the items currently traveling to it.
