### ISSUE TITLE
[1.18.2] Item dupe with storage drawers

### ISSUE THREAD

**Issue by Saereth** [Ellpeck/PrettyPipes#158]
![image](https://user-images.githubusercontent.com/9200909/194450146-64815887-5ec0-48b2-9cc3-16b1818e9e7d.png)

you can replicate it if you lock a drawer and have pretty pipes extract to it after temporarily unlocking the drawer

Im not sure if this is on pretty pipe's end or storage drawers however so reporting to both

Relevant versions: 
mc 1.18.2
forge: 40.1.80
pretty pipes: PrettyPipes-1.12.3
Storage drawers: StorageDrawers-1.18.2-10.2.1

https://github.com/jaquadro/StorageDrawers/issues/1045

**Comment by Ellpeck** [comment]
Hmm, I'm not sure I understand the steps to reproduce this issue. Could you elaborate a bit?

**Comment by Saereth** [comment]
This was report by the streamer Threefold I will attempt to reproduce this myself and get a more concise reproduction, will report back soon one way or another

**Comment by Saereth** [comment]
ok after updating to the latest pretty pipes I have been unable to reproduce this anymore
