### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by Sunekaer** [Ellpeck/PrettyPipes#162]
Crashlog: https://pste.ch/goverinuge.pl

### **Describe the bug**
Server crash when placing an entangled block next to a pretty pipe

### **Steps to reproduce**
1 Place pretty pipe
2 Place entangled block
3 Crash server

**Comment by Mattabase** [comment]
This crash occurs when an entanglement blocked in linked to a pretty pipe, not when placing next to. 

It also crashes again if the linked pretty pipe is updated

**Comment by Ellpeck** [comment]
Hi, same as #163, it seems like the stack trace is missing from the link you sent, or the site that hosts it changed, or something? Please re-submit the exception if you have it, or try to reproduce the issue if you can. Thanks!!
