### ISSUE TITLE
Console spam

### ISSUE THREAD

**Issue by Sunekaer** [Ellpeck/PrettyPipes#163]
### Log Files

https://pste.ch/egurexamak.pl

### Describe the bug

Console spam from an exception in pretty pipes

### Steps to reproduce

1. Use pretty pipes with item terminals while linked to drawers 
2. Console spam every time you open the terminal

**Comment by Ellpeck** [comment]
Hi! It looks like the paste is empty? Or the site changed? Either way, I can't fix this without a stack trace unfortunately!
