### ISSUE TITLE
Crafting grid JEI/REI recipe fill

### ISSUE THREAD

**Issue by Mattabase** [Ellpeck/PrettyPipes#164]
When hitting the question mark in REI it will often not populate the recipe, however when items are requested that are in the recipe some of the items will go to the grid instead of the item pickup slot in the GUI. Playing FTB Stoneblock 1.18.2

**Comment by Ellpeck** [comment]
I'm not sure what REI is, so I don't know anything about that issue. 

Can you try to reproduce this issue with just Pretty Pipes and Just Enough Items installed? If not, it might be worth trying to figure out which mod is influencing this issue.

**Comment by Mattabase** [comment]
REI is an alternative to JEI 

Will try to test with JEI and see if it persists 

https://www.curseforge.com/minecraft/mc-mods/roughly-enough-items

REI attempts to trick other mods into thinking it is JEI so the issue may be there.

**Comment by MissPotato** [comment]
Can confirm that REI tends to break the pretty pipes insert GUI. The whole terminal will go black, forget the items, then after about a second recover. It will work randomly but most of the time it just causes the whole terminal to freeze.

**Comment by shedaniel** [comment]
(REI Dev)
Please feel free to close this issue here, I will handle issues with JEI compatibilities on the REI side.
