### ISSUE TITLE
Crafting terminal

### ISSUE THREAD

**Issue by timog1320** [Ellpeck/PrettyPipes#165]
Hello everyone, I dont know if this is the correct forum but I need help with pretty pipes Crafting terminal, everything works fine however everytime i log off and log back in, when i go to get items nothing shows up, crafting terminal is empty, so i have to disconnect all pipes and connect them again it is so frustrating anyone know how to fix this?? thank you so much for the help

**Comment by Ellpeck** [comment]
Hi, please try to reproduce this issue without any other mods installed. Thanks!
