### ISSUE TITLE
It does not allow saving objects or items in storage and sometimes they are duplicated.

### ISSUE THREAD

**Issue by Gokku89** [Ellpeck/PrettyPipes#166]
Hello I have several bugs in my world, I am using the latest update of pretty pipes in 1.19.2, the first is that it does not accept some items or objects to be saved and the second is that sometimes it duplicates the items. I hope it can be fixed, because it is an excellent mod that has been very useful to me.

**Comment by Ellpeck** [comment]
Hi, could you please elaborate on your issues? One of the issues you described sounds like a duplicate of #181.
