### ISSUE TITLE
Request Item Duplicated In Some Storage

### ISSUE THREAD

**Issue by Christopher117** [Ellpeck/PrettyPipes#169]
Hi !

I use the mod with the Create mod, everything work fine exept for one thing.
In Create you have some very big storage called "Vault", these storages can be 3x9x3 blocs and can hold a lot of items.
When a request is done on a vault it work very well (at first). But if you log out and back in you will see that the item you just ordered is still in the vault (and in your inventory). The item has been duplicated.

I've noticed this issue on 1.18.2 and 1.19.2 with the latest versions of both mods.

Thanks for this awsome mod !

**Comment by Christopher117** [comment]
(Tested on Server and Solo !)

**Comment by Ellpeck** [comment]
Hi! Can you try to reproduce this issue in 1.20.1? Thanks!
