### ISSUE TITLE
Pipes issues with potions

### ISSUE THREAD

**Issue by janarjo** [Ellpeck/PrettyPipes#175]
I was directed to post this issue here from https://github.com/EnigmaticaModpacks/Enigmatica6/issues/5303

I have a sizeable item network for an entire village. I have storage hubs with retrieval modules for various items. Other retrieval modules for retrieving said items and using them in recipes/processing. Extraction modules are not used in this network. Multiple crafting terminals for interacting with the network. So far it's been working very well.

I have tested with following potions: Potion of Regeneration (II), Potion of Absorption (IV), Potion of Fire Protection, Potion of Resistance. Probably same issue with other potions.

Problems that I found:
1. Retrieval modules don't filter potions correctly. Seems it considers all potions equivalent and sends whatever potions it can get even when you filter for a specific type. Stack limiter does work correctly though, fortunately.
EDIT: I found out I can mitigate this with by using a Data Filter module. If this is the intended solution then perhaps this issue can be disregarded.

2. When requesting potions from a item/crafting terminal, it will send the correct type but everything at once even when you request only one. (It says it requests for 8 when I ask 1 or however many it finds) Since potions don't stack, this is not great.

3. Retrieval module requesting all 4 types of potions + stack limiter + data filter module dooes not seem to work together.
With stack limit of 3 it retrieves 3 of one type of potion and ignores the rest.

**Comment by Ellpeck** [comment]
>  EDIT: I found out I can mitigate this with by using a Data Filter module. If this is the intended solution then perhaps this issue can be disregarded.

This is the intended solution! As potions are all the same item, modules all treat them as the same item by default.
