### ISSUE TITLE
Crash when opening Compact Machine UI containing Pretty Pipes (1.18.2 - v1.12.8)

### ISSUE THREAD

**Issue by Lordmau5** [Ellpeck/PrettyPipes#184]
[crash-2023-03-24_13.59.15-client.txt](https://github.com/Ellpeck/PrettyPipes/files/11062280/crash-2023-03-24_13.59.15-client.txt)

They work fine *inside* the Compact Machine, but somehow the renderer for the Compact Machine UI causes my client to crash

**Comment by Lordmau5** [comment]
To quote the following issue: https://github.com/CompactMods/CompactMachines/issues/540

> Looking into this more, this looks like it's more an issue on both sides. While I can add the capability support on my rendering world, Pretty Pipes should be null-handling itself as well. Please report this to them as well!

Additionally I noticed this issue is actually a duplicate of #138

**Comment by Ellpeck** [comment]
Oh, it is a duplicate, that's true! I'll leave the other one open for now then.

**Comment by Lordmau5** [comment]
Alrighty! But yeah, I don't know if BlockPos is meant to be nullable (IntelliJ didn't want to show me the proper sources in my dev environment just now) but I assume a null-check in https://github.com/Ellpeck/PrettyPipes/blob/main/src/main/java/de/ellpeck/prettypipes/network/PipeNetwork.java#L483 and thus returning an empty list doesn't hurt just to be safe 🙏
