### ISSUE TITLE
not working I beleave 

### ISSUE THREAD

**Issue by Howman** [Ellpeck/PrettyPipes#189]
I am using MineColonies huts/chests and Iron chests to transfer items to a item sorter  it will pull from chests but not deposit to end chest,  you can see items going to chest but when you open nothing there not sure if it might be distance.

**Comment by Howman** [comment]
Is there some sorta time limt before they show in chest cause I went back to chest and some of the items where there.

**Comment by Ellpeck** [comment]
> Is there some sorta time limt before they show in chest cause I went back to chest and some of the items where there.

Sorry? Items travel slowly through pipes, you can see them traveling. There's no additional time limit.

**Comment by Howman** [comment]
I can see them travel fine but can not tell if they actually moved to the new chest. not sure the actual time it takes to show but I know it's 2 min plus cause I have waited for them to show in the chest after items have moved through the pipes they will not show but if i go away and do other stuff then come back at a later time items seam to be there

**Comment by Ellpeck** [comment]
Are you sure this isn't an issue with your server's TPS? Based on the tick rate, the items may appear to move faster than they actually do. If the TPS is under 20 (which is what it's supposed to be), issues like this may occur.
