### ISSUE TITLE
Questionable Icon Choice on Side of Crafting Terminal

### ISSUE THREAD

**Issue by EUdds** [Ellpeck/PrettyPipes#191]
![2023-08-26_10 39 20](https://github.com/Ellpeck/PrettyPipes/assets/8378883/037133a7-efed-4c7d-a402-f8d473e02724)

I see what you were going for, I'm not trying to cancel anyone, but the art choice on the crafting terminal looks like a [Swastika](https://en.wikipedia.org/wiki/Swastika).

**Comment by Ellpeck** [comment]
That's [not the vanilla Pretty Pipes texture](https://github.com/Ellpeck/PrettyPipes/blob/main/src/main/resources/assets/prettypipes/textures/block/crafting_terminal.png). I kind of agree, though.

**Comment by EUdds** [comment]
Ope - must be the modpack. Noted!

**Comment by EUdds** [comment]
fwiw - see the patched textures for the [UniverseIO pack](https://www.curseforge.com/minecraft/modpacks/universio/files) here
