### ISSUE TITLE
[Question] Retriever without filter

### ISSUE THREAD

**Issue by Adam-Kay** [Ellpeck/PrettyPipes#198]
Hi, I'm using Pretty Pipes 1.12.8 on Minecraft 1.18.2, and I was wondering if there was some way to have the retrieval module retrieve all without a filter?

I'm using a scenario like the diagram below, where `X` is the chest with a retriever attached, and `C` are chests with just pipes attached to them. 

```
      X
      |
-------------
 |    |    |
 C    C    C
```

Can I have the retrieval module at X just pull everything from all 3 Cs? If there are 10 chests like C, it would be more efficient to have one retriever rather than 10 extractors. Please let me know if this is somehow possible and I missed it. If not, please treat this issue as a suggestion.

**Comment by Ellpeck** [comment]
Hi :) Retrieving from multiple containers without a filter is not supported, and there are no plans to support this behavior. Sorry!
