### ISSUE TITLE
Feature Request: fluid transport

### ISSUE THREAD

**Issue by erisdev** [Ellpeck/PrettyPipes#20]
I have a few thoughts:

- dedicated fluid pipes
- a module that makes a pipe pull fluids instead of items
- all pipes can pull fluids by default

In the latter two cases, I'm imagining pulling lava and items into the same pipe would destroy the items. In either case, a way to pull fluids from in-world would be hella, but I don't need tanks or anything like that since there are already plenty of mods that offer just tanks.

**Comment by Ellpeck** [comment]
No, sorry.
