### ISSUE TITLE
Adding a mod for Fabric

### ISSUE THREAD

**Issue by karlmark2003** [Ellpeck/PrettyPipes#207]
I would like to ask if it would be possible to add a launcher for Fabric, specifically version 1.20.4

Thank you

**Comment by Mrbysco** [comment]
If memory serves me correctly there were no plans on making a fabric version. Although I'm not sure if that has changed since the comment.
https://github.com/Ellpeck/PrettyPipes/issues/174#issuecomment-1364548487

**Comment by Ellpeck** [comment]
Unfortunately, Mrbysco is correct, and there are no plans on making a Fabric version. The effort that would have to be put into a port, as well as maintaining both versions (be that separately or with an abstraction layer) would be too great. Sorry!
