### ISSUE TITLE
Numbers on Pipe Frame are hard to read

### ISSUE THREAD

**Issue by fr3qu3ncy-dev** [Ellpeck/PrettyPipes#216]
![Screenshot_255](https://github.com/user-attachments/assets/9ea54c50-0cc0-4f1b-8139-cd5a08706ae0)

There seems to be an issue with the dropdown shadow of the pipe frame's text, it seems to be glitching in front of the actual text.

Used version: 1.18.0
Loader: NeoForge 21.1.73
No resource pack used
Other mods:
- Fabric Connector
- Continuity (resource pack disabled)
- Forgified Fabric API
- Iron Chests
- JEI
- Xaero's Minimap
- Xaeros's World Map

(Also tried with all other mods disabled, no resource pack, still same issue)

**Comment by fr3qu3ncy-dev** [comment]
Fixed in PR #217

**Comment by Ellpeck** [comment]
closed by #217
