### ISSUE TITLE
Feature Request: Pipe covers

### ISSUE THREAD

**Issue by lbowenwest** [Ellpeck/PrettyPipes#24]
First off, big fan of the mod thanks. One feature that I find myself wishing for when using these pipes, is the ability to add covers to them to integrate them within my builds and be able to hide the pipes within walls. 

One way I thought of adding this would be to add a frame (similar to the pipe frame that already exists) that you can attach to pipes, and be able to right click a block onto to cover it with that texture.

**Comment by Ellpeck** [comment]
Resolved by https://github.com/Ellpeck/PrettyPipes/commit/ff5368b108c36d5a9cc89ac7e2a4f528c3e388ea
