### ISSUE TITLE
Error Crafting Terminal

### ISSUE THREAD

**Issue by ArturilloD** [Ellpeck/PrettyPipes#25]
When in the crafting terminal, in the crafting grid in some box there is a stack, the game is blocked, it does not crash, but it freezes.

Forge: 31.2.36
Minecraft: 1.15.2
Pretty Pipes: 1.5.4

**Comment by Ellpeck** [comment]
what

**Comment by ArturilloD** [comment]
As I tried to explain in the previous message is that when in the crafting table of the terminal crafting in any of the 9 boxes there is a stack (x64) of any element the game is frozen, the entities remain immobile and the chests and others blocks with UI cannot be opened.

**Comment by Ellpeck** [comment]
I'm really not sure what you mean. Could you share some screenshots or a video and attach your logs?

**Comment by ArturilloD** [comment]
The last time I tried it, it did not happen, so I suppose it is
incompatible with a mod, when I find it I record the video, the game froze
when the grid was filled with a stack in some box, but remember badly also
in the one of departure

**Comment by Ellpeck** [comment]
This issue has gotten stale, so I'm closing it for now. If the issue still persists, please reopen it.
