### ISSUE TITLE
Pipes

### ISSUE THREAD

**Issue by ArturilloD** [Ellpeck/PrettyPipes#27]
I would like to know if there is any possibility to allow the Pretty Pipes to send more than one stack at the same time.

**Comment by Ellpeck** [comment]
No, there isn't. You can always connect multiple pipes to the same container.

**Comment by ArturilloD** [comment]
That which says to put several pipes does not work, since it detects the
fastest route and keeps sending stack by stack. By the way, the pipes do
not distribute the items well when they are sent to an entity that is
extracted to send it to another, for example when I send it to a hopper and
that hopper to another or to an automatic work table for some reason it
does not distribute in equal parts.
