### ISSUE TITLE
pipes expelling item

### ISSUE THREAD

**Issue by Mariatti** [Ellpeck/PrettyPipes#32]
the cables are expelling several items through the middle of the cable and through the curves even making the correct path

**Comment by Ellpeck** [comment]
What?

**Comment by Mariatti** [comment]
See
[](https://prnt.sc/u84q3w)

**Comment by Ellpeck** [comment]
Items will only fall out of pipes when they reach a destination that doesn't have any space left, then turn around, and the origin also doesn't have any space left. I assume what's happening here is that you're using a low tier extraction module, which doesn't prevent over-sending.
