### ISSUE TITLE
add a comfig to allow more items so be extracted please. 

### ISSUE THREAD

**Issue by chyper111** [Ellpeck/PrettyPipes#34]
9 items is to few. the gui has room for 3 rows and there's no config to change how many you want to sort and a chest only has so many sides. please add a config or just add more slots.

**Comment by Ellpeck** [comment]
Just add more pipes to your container.

**Comment by chyper111** [comment]
no it doesnt have enough sides for that

**Comment by chyper111** [comment]
why make the gui so big if you cant add two more rows

**Comment by Ellpeck** [comment]
Then use a different pipe mod.

**Comment by Ellpeck** [comment]
It kind of feels to me like you don't know that, for Extraction modules, you can just leave the filter empty to allow *all* items to be extracted from the container.
