### ISSUE TITLE
Error in the transport system

### ISSUE THREAD

**Issue by ArturilloD** [Ellpeck/PrettyPipes#35]
The pipes eject the transported elements out of the system, it occurs when the pipes try to insert items into a container and I don't know very well if it is because it is already full or something similar, then it seems as if I wanted to return to the place of origin, although instead it's like the pipes have an element limit or something like that and instead of going into the container they just fly (literally) out of the system and float to the ground. If you require it then I could send you a video. Regards

**Comment by Ellpeck** [comment]
You need to use modules that prevent over-sending. The description of the modules states if they do, so you can just search "over" in Just Enough Items (if you have that installed) to find all the ones that prevent over-sending.

**Comment by ArturilloD** [comment]
I have tested it with the stack limiter module and unless small numbers are
entered that continues to happen

**Comment by Ellpeck** [comment]
When using the stack limiter module with a higher amount than the items' maximum stack sizes, the extraction/retrieval module used to insert into the containers also needs to prevent over-sending. If that is the case for you, and the issue still occurs, then please re-open this issue.

**Comment by ArturilloD** [comment]
I think I have discovered what happens, apparently it is with the Workbench
Factory (https://www.curseforge.com/minecraft/mc-mods/workbench-factory),
it has the exit slot and they do not allow you to enter items, the others
do not work, since the output item is different from the input item, so
they end up jumping.

Demo video: https://youtu.be/XQ51T-voYAY

By the way, as a note or suggestion is to say that the ender chests cannot
be connected to the pipes. Greetings and thanks

**Comment by ArturilloD** [comment]
The problem persists. To replicate it is very simple with Storage Drawers (
https://www.curseforge.com/minecraft/mc-mods/storage-drawers), since the
drawers do not accept a lot of variety of items.

Steps to reproduce it:
 1.- Put a chest with different items and to make it faster that they are
not stackable or put one or two of each one.
 2.- Put several drawers connected to that chest.
 3.- Send those elements to the drawers.
 4.- Cut the outlet pipe of the chest when some items have come out.
 END - At that moment the elements that are in the pipe will jump out.

Why it occurs:
The collapse occurs since several elements go out towards the same chest /
drawer, then one type of item enters the drawer chest, then two things can
happen here:
 1.- The item cannot enter because that chest / drawer is already full or
blocked because another type of item cannot enter
 2.- The outlet box is full or the pipe no longer exists and then the
element has no "place to go" and jumps out of the system.

How to solve it:
The problem occurs when the element is blocked because where it was
assigned to enter it cannot and then it returns to the original chest to be
reassigned another destination, at that moment if the chest from which it
has left is full the element jumps out of the system and is lost, a
possible solution would be for that element to look for another chest /
drawer where it could enter before returning to the original chest / drawer
or not to leave without confirming that it will surely be able to enter,
since that way it does not leave the slot empty and it doesn't allow you to
enter any other element in its place, so that way you don't have a place to
stay.

**Comment by Ellpeck** [comment]
Just to confirm: You are using extraction/retrieval modules whose tiers *prevent over-sending*, that is: An extraction module of at least tier 3, or a retrieval module of at least tier 2, correct?

**Comment by ArturilloD** [comment]
Right, it even happens by also putting a stack limiter
