### ISSUE TITLE
Can we have some documentation, please?

### ISSUE THREAD

**Issue by alfuken** [Ellpeck/PrettyPipes#55]
Or at least a few example setups would be nice. Like, autocraft with crafting table, autosmelting, smelting on-request, stuff like that. Because currently it's totally unclear how to use this mod.
Thanks!

**Comment by Ellpeck** [comment]
I made this video about auto-crafting today. Have fun!

https://www.youtube.com/watch?v=wC6pEgNGXGg&feature=youtu.be

**Comment by alfuken** [comment]
Great, thanks!
