### ISSUE TITLE
Feature request: autocrafting

### ISSUE THREAD

**Issue by alfuken** [Ellpeck/PrettyPipes#56]
Would be great if you could add to the mod some autocrafting table, like https://github.com/SHsuperCM/SimplyCrafting , for example.
Or implement this as a "Crafting Node", block that connects to the network, has grid like in crafting table, in which you can layout the recipe, and crafts items as requested.

**Comment by Ellpeck** [comment]
Nope, sorry. I don't think that fits the mod well. If you want autocrafting, just install one of the many mods that provides a great one.

**Comment by alfuken** [comment]
Hah, well, that's the thing - there is none, and that's why I'm asking. :)
There's only 1 mod that provides something similar to autocrafting for 1.16.2, https://github.com/Lolcroc/ProjectLepton , but it's completely incompatible with prettypipes — it ejects the result by itself, and crafts only on receiving redstone impulse. All other autocrafters are either outdated (as SimplyCrafting, for example), or they're part of other big mod, like the one you used in your video.

**Comment by Ellpeck** [comment]
That Autocrafting table looks pretty good to me! You'd just have to either connect it to a clock or create a setup where you use a comparator to detect when items are going through the pipe.

**Comment by alfuken** [comment]
aaand that's already overcomplicates things way more than I'd like... Oh well, I guess I'll have to write one myself...

**Comment by Ellpeck** [comment]
If you want a super simple item storage mod, you probably shouldn't have gone for Pretty Pipes :p

**Comment by alfuken** [comment]
Well, it's not only storage, but automation, too. This is so far the best mod for that kind of things since Buildcraft and RedPower (Project Red) got outdated. I really love to see those items moving around through pipes over my head here and there. Much more enjoyment than soulless AE...
