### ISSUE TITLE
Having too many modules in one area causes "NBT tag too big" crash

### ISSUE THREAD

**Issue by gkatoh1** [Ellpeck/PrettyPipes#58]
I was kicked from the game and got this message. After looking at the area with NBT Explorer I found that there were many entries with pipes and modules. I removed the entities with NBT Explorer and I was able to join the world again. 

![error](https://user-images.githubusercontent.com/73512061/99461343-81c9b080-28e6-11eb-9135-710ff6b900b3.PNG)

**Comment by Ellpeck** [comment]
Are you sure this didn't happen when trying to open a terminal? That's pretty much the only case where a lot of NBT data gets sent.

**Comment by gkatoh1** [comment]
Yeah I don't have a terminal. This is what I saw yesterday when I checked NBT Explorer. I had about 4 stack limiters, 8 retrieval modules, and 2 extraction modules within a 2x2 chunk area
![IMG_3444](https://user-images.githubusercontent.com/73512061/99463801-6ca35080-28eb-11eb-8ef8-8e6ae04ab3b9.jpg)

**Comment by Ellpeck** [comment]
Nothing looking out of the ordinary there. Can you send the broken region file so I can investigate for myself?

**Comment by gkatoh1** [comment]
The chunk was at -107,65. Unfortunately this is the one with the deleted entries that I uploaded to my server. Everything else is untouched

https://gofile.io/d/Q7KMMx

**Comment by Ellpeck** [comment]
The fixed file won't really help me, sadly. Do you have any NBT-heavy items in the filter slots of your modules (stuff like enchanted books or other things that store additional data), and do you do any auto-crafting using the retrieval modules you mentioned?

**Comment by gkatoh1** [comment]
My filter slots were for bonemeal, poppy, poisonous potato, iron, wheat, sugarcane, coal and there was no auto crafting

**Comment by Ellpeck** [comment]
It is almost impossible that that setup caused the exception to occur. It was probably caused by another mod, and removing the Pretty Pipes data just happened to push it back below the limit. 

If this exception occurs again, please be sure to save the region file and re-open this issue :)
