### ISSUE TITLE
Feature Request: Stack limitation for items in filter modules

### ISSUE THREAD

**Issue by PfefferT** [Ellpeck/PrettyPipes#6]
Let's say you have a chest with extraction module and a chest with a filter module which allows only steaks and chicken then you are not able to determine the stack limit module for the steak and the chicken itself

**Comment by Ellpeck** [comment]
What? If you put a stack limiting module into the receiving pipe, any item in the chest will be limited by that module.

**Comment by PfefferT** [comment]
The thing I want is:
filter module which allows chicken and steaks
chicken should not be more than 64 and steaks not more than e.g. 32 .

**Comment by Ellpeck** [comment]
Just connect two pipes to your inventory instead of 1.

**Comment by PfefferT** [comment]
this was just an example for determining my problem. I have partially much more inside the allowed part.

hm okay then lets say:
allow chicken, steaks, wheat, bread, and fish

chicken should hold 64
steak 48
wheat 32
bread 16
fish 8
