### ISSUE TITLE
Items get stuck in pipes 

### ISSUE THREAD

**Issue by Dasavanth** [Ellpeck/PrettyPipes#60]
mod version: 1.8.2

issue: 
items get stuck in pipes when two inventories are connected to same block (only tested with crafting terminal and modular storage)

steps to reproduce:
1. connect crafting terminal and any  inventory to the same pipe
2. try sending items through crafting terminal
3. they probably are stuck in the pipe

**Comment by HorribleNerd** [comment]
Can confirm, moving the crafting terminal one block further fixes it. Multiple inventories connected to the same pipe works fine, just not when one of those is the crafting terminal.
