### ISSUE TITLE
[feature request] compat for other storage mods, specifically RS and AE

### ISSUE THREAD

**Issue by KrAzYGEEK32** [Ellpeck/PrettyPipes#63]
i know this is pretty far fetched but it would be awesome if a pipe connected to an interface of AE or RS could read the entire content of the network, like how logistics pipes does in 1.12 with AE2. saw it was never asked before so im just making sure if it has any remote possiblity to be a feature. love the mod and you :heart:

**Comment by Ellpeck** [comment]
I don't really think this fits the mod's theme.
