### ISSUE TITLE
Tag based filter doesnt work

### ISSUE THREAD

**Issue by Dasavanth** [Ellpeck/PrettyPipes#66]
mod: 1.9.0
MC: 1.16.4
forge: 35.1.13

issue:
tag based filter doesnt seem to behave as intended, images for reference
![2020-12-21_21 22 51](https://user-images.githubusercontent.com/69692930/102796799-cdcfaf80-43d4-11eb-9f9d-bae315abdb26.png)
![2020-12-21_21 22 52](https://user-images.githubusercontent.com/69692930/102796808-d2946380-43d4-11eb-829b-0d5712759f15.png)
as far as i understand, this setup should redirect all items tagged as forge:ingot or forge:nugget to the connected inventory but this doesnt happen

**Comment by Ellpeck** [comment]
The item entering the pipe needs to have **all** of the tags on the filter item, not just one.

**Comment by Dasavanth** [comment]
do you mean they have to be a perfect match?

**Comment by Ellpeck** [comment]
No. The tags on the item in the filter has to be a subset of the passing item's tags.
