### ISSUE TITLE
Pipes don't seem to interact with hoppers or any autoejecting blocks trying to push into them

### ISSUE THREAD

**Issue by Dasavanth** [Ellpeck/PrettyPipes#67]
mod: 1.9.0
MC: 1.16.4
forge: 35.1.13

issue:
pipes aren't accepting items from autooutputting blocks like hopper (machines from thermal series and mekanism are some modded examples). Might be a design choice but making an issue just in case. :)

**Comment by Ellpeck** [comment]
This is intended behavior.
