### ISSUE TITLE
Feature Request: power machines with pipes

### ISSUE THREAD

**Issue by PfefferT** [Ellpeck/PrettyPipes#7]
At the moment it is not possible to put coal and iron ore into an furnace with 2 pipes and extract the iron bars with a third pipe

**Comment by Ellpeck** [comment]
Cannot reproduce, this is perfectly possible. There's even an image on the mod's page..

**Comment by PfefferT** [comment]
To reproduce this:

1 chest with iron ore and coal -> extraction filter with disallow nothing
pipe into the bottom of the furnace with filter module on coal
same pipe got an branch into the top of the furnace with filter module on iron ore
on the right side of the furnace a pipe goes into a chest. the furnace got here an extraction module.

In my case the coal goes an infinite loop -> I have a more complex pipeline sorting system as input pipeline
