### ISSUE TITLE
Let camouflaged pipes connect to connecting blocks like panes.

### ISSUE THREAD

**Issue by KrAzYGEEK32** [Ellpeck/PrettyPipes#70]
![2021-01-10_13 07 34](https://user-images.githubusercontent.com/59537798/104123864-80ab8180-5373-11eb-826a-39930dbd6c7a.png)
this should expain it better than my shabby title.
it would be nice if the pane connected to the camouflaged pipe.
same would apply to walls and fences.

**Comment by KrAzYGEEK32** [comment]
just in case you consider this as a bug
mod: 1.9.1
forge: 35.1.6
MC: 1.16.4

**Comment by Ellpeck** [comment]
Le sigh.
![image](https://user-images.githubusercontent.com/5741138/107099716-b462b580-6812-11eb-9a2f-5d939ff9e8d9.png)

**Comment by KrAzYGEEK32** [comment]
😘😘
