### ISSUE TITLE
Recursive autocrafting not working

### ISSUE THREAD

**Issue by cwrau** [Ellpeck/PrettyPipes#71]
Hello, 

First of all, cool mod! Really nice early-game storage system!!

Now to my problem; 

I set up a couple of crafting recipes, e.g. your `Medium Crafting Module`.

I set up all the dependant recipes as well, everything using rftools crafters.

Now when I request a medium crafting module, it complains that `Low Crafting Module` is not found. 

When I manually go down the crafting tree it complains about `Redstone Servo`s and such, but I can fix all errors just by requesting the item.

To make it clear, I'm *not* crafting the dependant recipes, just requesting them from the terminal.

**Comment by Ellpeck** [comment]
Please try to reproduce this issue with version `1.9.0` of the mod.

**Comment by cwrau** [comment]
It works with version 1.9.0

**Comment by Ellpeck** [comment]
It would be great if you could re-attempt with this version, which I *think* might fix this issue. 
https://ci.ellpeck.de/blue/organizations/jenkins/PrettyPipes/detail/main/22/artifacts

**Comment by cwrau** [comment]
Sadly this didn't fix the problem 😕

**Comment by Ellpeck** [comment]
Hmm.. can you show the "recipe tree", ie all of the recipes required to craft the thing you're trying to craft? JEI screenshots are fine.

**Comment by cwrau** [comment]
Sure;

![2021-02-05T22:31:57 33](https://user-images.githubusercontent.com/14326070/107091567-4b734180-6802-11eb-9946-0f11c6c3a5b6.png)
![2021-02-05T22:32:09 29](https://user-images.githubusercontent.com/14326070/107091592-54fca980-6802-11eb-95d2-214130738f57.png)
![2021-02-05T22:32:03 86](https://user-images.githubusercontent.com/14326070/107091598-56c66d00-6802-11eb-87d9-2f202a76dc4c.png)
![2021-02-05T22:32:00 34](https://user-images.githubusercontent.com/14326070/107091600-575f0380-6802-11eb-8f41-65b6fa741518.png)


I also screenshotted the crafting configuration;

![2021-02-05T22:33:13 31](https://user-images.githubusercontent.com/14326070/107091625-62199880-6802-11eb-8033-de00d05d33cc.png)
![2021-02-05T22:33:10 63](https://user-images.githubusercontent.com/14326070/107091630-634ac580-6802-11eb-83c3-76dbebb80b66.png)
![2021-02-05T22:32:27 14](https://user-images.githubusercontent.com/14326070/107091632-63e35c00-6802-11eb-905c-f41e0917cc2b.png)
![2021-02-05T22:32:24 83](https://user-images.githubusercontent.com/14326070/107091633-647bf280-6802-11eb-96fd-3aee12ad1432.png)

**Comment by Ellpeck** [comment]
Oookay, what about this version?
https://ci.ellpeck.de/blue/organizations/jenkins/PrettyPipes/detail/main/23/artifacts

**Comment by cwrau** [comment]
Nice, that seems to be working!
