### ISSUE TITLE
Weird item dupe/item deletion with a combination of mods

### ISSUE THREAD

**Issue by MissPotato** [Ellpeck/PrettyPipes#72]
Really bizarre bug that I can't seem to reproduce. Two of the drawers in my mob grinding station has been completly replace by horse armor. I'm not certain if it's storage drawer's fault, pretty pipe's fault, quantum storage's fault or some rogue bit flip.  

Everything was working fine originally, I had no problems with the setup until I increased the number of spanners being used. When I increased the spawners a high speed extraction module couldn't keep up with the speed the input Quantum Storage Crate was having items added to it. I tried adding extra modules to the pipe connected to the create but that isn't possible. So then I tried adding a retrieval module to the Storage Drawer Controller and that just prevented it from getting items from the Extraction Module's pipe.  I then tried adding another pipe that resulted in the same issue of not being fast enough. I then tried adding a second extraction module to the second pipe connected to the Quantum Storage Create and while that solved my issue of not keeping up it caused all my bones and arrows to be replaced by gold and iron horse armor.  Resulting in a drawer completely filled with it. 

The weirdest thing is AFAIK there is no way I could have even gotten horse armor to begin with. I've been manually emptying the chest for half an hour  while trying to figure the bug out and not a single horse armor has come through.

I'm thinking it has something to do with the controller for storage drawers as it really doesn't seem to play well with pretty pipes. The chest with the horse armor is one of the only chests that had a void upgrade. And it also almost never received the excess bones until I connected it directly to the PP network.

**Comment by Ellpeck** [comment]
Pretty Pipes couldn't possibly have created an item that doesn't even drop at all out of thin air, so I really doubt this is at all related.

Regardless of this, Storage Drawers hasn't been making use of item handlers in the correct (intended) way for a very long time, so it doesn't play nice with most pipe mods. I recommend trying out Mekanism's bins, QuantumStorage storages or Industrial Foregoing's mass item storage.

**Comment by MissPotato** [comment]
Should I report this to storage drawers?
