### ISSUE TITLE
No Data Fixer

### ISSUE THREAD

**Issue by RainnMannx** [Ellpeck/PrettyPipes#74]
PP 1.9.2
Forge 36.0.14
MC 1.16.5

[Render thread/ERROR] [minecraft/Util]: No data fixer registered for pipe_frame

If it can be fixed great, if not that's ok also, seems this is not really an error? Just OCD on the warning in the logs =P

**Comment by Ellpeck** [comment]
That's not an error, it's just something Minecraft complains about. Data fixers fix data when the game updates, but since modded worlds are incompatible 99% of the time with different game versions anyway, modders don't really care about them.
