### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by MarobsKoco** [Ellpeck/PrettyPipes#75]
On my game and server pretty pipes stopped working. pipe and stuff are still there. but if i open the terminal or crafting terminal. i dont see the items i had stored. and when i want to empty a chest it dosent suck the item out any more and stuff like that, please fixe this.
date: 19-02-2021
Last update dont work with 1.16.5
![fout](https://user-images.githubusercontent.com/64714142/108471420-a9d10300-728b-11eb-991b-2f21c127d5ac.jpg)

**Comment by Ellpeck** [comment]
Please try removing and replacing your pipes to see if that fixes the issue.

**Comment by MarobsKoco** [comment]
Realy...??? Do u know how much work it is to replace every single pipe. Months of work, I have a huge system that run all, and most of it is hidden. so u want me to break every thing open and replace all the pipes? I think this is a little bit of crazy. dont u think? Every thing workt till the last update. Dont want to replace all the pipe every update, that would be crazy. I didnt change any thing, so why it stopped working i dont know. But it should just work as it should be even after an update. No one wants to replace Miles and miles of pipe!

**Comment by Ellpeck** [comment]
ok
