### ISSUE TITLE
Items disappearing when transferring into terminal interface

### ISSUE THREAD

**Issue by shibeobi12** [Ellpeck/PrettyPipes#76]
I'm not quite sure how to prove this through a log or a video if I manage to catch it, but since the version 0.4.1 Enigmatica 6 debuted, I occasionally lose items when requested them. All I can tell after testing is that it might be related to when you ask for 64 of something that doesn't have that much. Still testing as I go to see if it happens using exact numbers... If there's anything else I can gather let me know. Hopefully this is the right spot!
My most recent example:
Had 44 wheat in a vanilla chest hooked up to pipes, only a low speed extractor on a pipe attached, along with a pipe pressurizer.
Requested 64 with the shift click, I got exactly half the stack instead, and the other 22 disappeared.

I tried to leave the server and reconnect afterwards to see if it was client-side, it doesn't appear to help.

**Comment by Ellpeck** [comment]
If you can't consistently reproduce this issue, it'll be hard for me to attempt to fix it. I think your best bet would be to try to recreate a simpler version of your current setup in a creative world and narrow down what exactly might be causing the issue. Any slight anomalies you find would help, really!

**Comment by shibeobi12** [comment]
Well, about 30 minutes in creative and I'm really unable to replicate it. Maybe something going on with the server? I'll keep at it and let you know.

**Comment by shibeobi12** [comment]
Alright, definitely seems like it's something server side, or maybe setup wise. I just had two happen in a row, one was using 64 to request a smaller set, and the other was an exact retrieval amount, both halved the items on retrieval. I'll see if I can clone the server world and test locally.

**Comment by Ellpeck** [comment]
Do you have your chests connected to the network twice? That would explain the double item reports.

**Comment by shibeobi12** [comment]
Interesting, I'll double check. Sorry about that, I get the feeling that it
is that.... I tried to be too compact!

**Comment by shibeobi12** [comment]
Yup, I see what happened in my setup. I'm sorry for taking up your time. Thanks for working through it with me.
