### ISSUE TITLE
Create - Pretty Pipes Crash

### ISSUE THREAD

**Issue by NillerMedDild** [Ellpeck/PrettyPipes#77]
Hi there! I'm relaying this issue mostly as information, I'm not anticipating a fix since Pretty Pipes isn't doing anything incorrectly afaik :)

Relayed from https://github.com/NillerMedDild/Enigmatica6/issues/1581

PrettyPipes-1.9.3

> **Describe the bug**
> A clear and concise description of what the bug is.
> I had a Pretty Pipes pipe network hooked up to a diamond chest and Create's furnace engine's furnace block above Create's minecart converter. Everything was superglued together. I had several modules installed in the pretty pipes including Low Extraction, Low Retrieval, and Medium Retrieval on three sides of the furnace for logs and charcoal management. There were no items currently being transferred through the pipe network when I flipped the lever. Upon flipping the lever to convert, I immediately crashed to desktop. I believe the chunk is now corrupt and thus the server has been soft-locked until I delete and regen the chunk which will be fun to learn. I tested it many times before I installed the Pretty Pipes network and it had worked fine.
> 
> **Logs**
> Input pastebin link to crash-report or `latest.log`, if applicable.
> https://paste.ee/p/we5oo
> [crash-2021-03-07_16.27.32-client.txt](https://github.com/NillerMedDild/Enigmatica6/files/6097994/crash-2021-03-07_16.27.32-client.txt)
> 
> **Screenshots**
> If applicable, add screenshots to help explain your problem.
> N/A. Sorry, I didn't screenshot anything before I flipped the lever.

**Comment by Ellpeck** [comment]
This doesn't look to be a Pretty Pipes issue, so closing this for now.
