### ISSUE TITLE
Feature Request: Directional Pipes

### ISSUE THREAD

**Issue by mouse0270** [Ellpeck/PrettyPipes#8]
I loved the idea of this mod and took the time to update my entire underground item networking system with this (this mod is so much easier than water with packed ice). However I noticed that sometimes items pull in the wrong direction. For example, oak wood always seems to get pulled into the XPs lava pit instead of the chest that is only a few blocks from where I input the oak logs.

Like everything else seems to go the right direction and into the right chest, but both oak and dark oak wood/planks seems to go the wrong direction, even after adding the Retrieval Module for oak wood. It would be nice if we could say that a pipe can only pass items a specific direction. Though I think that would complicate the "over sending" issue because items might get stuck in a pipe.

**Comment by Ellpeck** [comment]
I don't really like this idea, sorry.
You could always use a filter module with a blacklist on the pipe that the wood is erroneously going into, though!

**Comment by mouse0270** [comment]
Could you help me understand why it is only oak and dark oak that does this? Literally every other black goes into their corresponding chests. Only Oak and Dark Oak wood/planks. 

I am going to step an a second server tonight with just this mod installed to see if its a bug with another mod or if for some reason oak is wonky in your mode. Like I said, I added a retrieval module and it still wont call oak into the chest, but will try and send it to the dropper for the XP farm. So I am not sure what's happening.

**Comment by Ellpeck** [comment]
A retrieval module won't extract from a chest that has an extraction module attached to it, so that might be the issue in your case.

**Comment by mouse0270** [comment]
I just took the extraction module off the chest input just and added retrieval modules to the storage chest for that type of wood. Now none of the wood is going to their correct chests. And the extraction module back in the spruce wood goes to the spruce wood, but oak wood stays in the input chest. 

It might be a conflict with another mod, I will rebuild my system on another server with just your mod and see how it works. If it works fine, its a mod conflict. If not, I will at least have a world with the issue that I can either invite you to or send to you for debugging.
