### ISSUE TITLE
Tab Order Feature Request

### ISSUE THREAD

**Issue by dannydjdk** [Ellpeck/PrettyPipes#80]
When hitting the tab key in the terminal, it would be amazing if the first field selected were the search field. Currently, when hitting the tab key, it first goes to the "+" button, then 2 of the buttons on the left, then each item in the inventory grid, and then the search field, so it's necessary to manually click the search field when entering the grid.

**Comment by Ellpeck** [comment]
Closed by https://github.com/Ellpeck/PrettyPipes/commit/f8b618a1d24dd5ea960f3f74fd18144f7fc1bab2
