### ISSUE TITLE
Storage Drawers not used correctly

### ISSUE THREAD

**Issue by Sadragos** [Ellpeck/PrettyPipes#81]
When using Highest Extractor Modules and Item/Crafting Tables they do not alwas sort into a Storage Drawer Controler even if there is more than enough space in the drawer. Only one of the Stacks goes in. Every other stack sent after that will go to the next Inventory aslong as the first stack is traversing the pipes on way to the drawer. When the first stack enters the Drawer and anther Stack is sent it entery the Drawer again correctly. 

This problem does not occur with Low or Medium Extracor Modules.

**Comment by Ellpeck** [comment]
This appears to be an issue with storage drawers.
