### ISSUE TITLE
Items don't get routed back when destination inventory is destroyed

### ISSUE THREAD

**Issue by Quarris** [Ellpeck/PrettyPipes#82]
https://user-images.githubusercontent.com/6171764/118709117-7e22d200-b814-11eb-8e7f-e8ad13080023.mp4

The items should be routed back to its original container but instead are being dropped.
This is caused when the item reaches the end and call onPathObstructed in PipeItem [here](https://github.com/Ellpeck/PrettyPipes/blob/e9b38d0df5aa8de67332fac24bb4126ec1be8bd2/src/main/java/de/ellpeck/prettypipes/network/PipeItem.java#L186)
This in turns calls routeItemToLocation in PipeNetwork [here](https://github.com/Ellpeck/PrettyPipes/blob/e9b38d0df5aa8de67332fac24bb4126ec1be8bd2/src/main/java/de/ellpeck/prettypipes/network/PipeNetwork.java#L169) which checks if the starting position (now just a pipe with no inventory) is a node (which is isnt anymore) and therefore doesn't attempt to route the item back.

Causes this for PP Fluids https://github.com/Quarris/PrettyFluidPipes/issues/2

**Comment by Ellpeck** [comment]
This is intended behavior.
