### ISSUE TITLE
[Feature] Pipe pressuriser  

### ISSUE THREAD

**Issue by ianwijma** [Ellpeck/PrettyPipes#84]
Hey! 

First off, loving the mod! Because its great to have in a modpack without any authentic power generation.

I have a pack which has beside a bunch of adventure and building mods, not any authentic power mods. I do have the Create mod installed. But that one does not generate any power like RF. So the pipe pressuriser doesn't do anything for me.

So this made me think of how to solve this. One way is to disable it, another idea was to utilise Create power beside RF.

I'm willing to help creating this feature, it will be a nice way to learn some more Java for me. So let me know! 

 
Many thanks,
Ian Wijma.

**Comment by Ellpeck** [comment]
I'm sorry, but the pipe pressurizer will only support FE for the foreseeable future.
