### ISSUE TITLE
Is there a command to reload filters or reload the mod?

### ISSUE THREAD

**Issue by khamseen** [Ellpeck/PrettyPipes#86]
I seem to be frequently running into an issue on a server I'm using where adding items to a filter module will not acknowledge those items and allow them to be passed into the attached containers mid game. I have to restart the server for it to update, this is time consuming and not overly practical to do regularly so I was wondering if there is a command to refresh filters or reload the plugin without having to completely restart the server.

**Comment by Ellpeck** [comment]
Cannot reproduce this issue. Please try to reproduce it with just Pretty Pipes installed.

**Comment by khamseen** [comment]
I'll try, the problem is it doesn't happen when the server first boots up. I'm not sure if it's a time issue or something like when I move away and come back it stops working. Will have to do some more testing I guess as it's super weird.
Any time I add a brand new filter and add items it'll work, but then after that if I try to add new items to the filter it just wont register those new items when dumping them into the system. 
If I can figure out what triggers it I'll get back to you.

**Comment by Sadragos** [comment]
I can confirm this Problem. When the Server is running for a while newly added or modified filters & prio modules wont be recognized. I can't however reproduce this behavior in single player with the same modpack.

**Comment by Ellpeck** [comment]
Please send the full server log of a session where this happened, as well as the full client log of a client experiencing these issues.
