### ISSUE TITLE
1.12.2?

### ISSUE THREAD

**Issue by ThatCrazyDad** [Ellpeck/PrettyPipes#87]
Just wondering if it were possible to get a 1.12.2 version.  I love this mod and it has been apart of a collection of mods I used for 1.16.5, but now i've moved to 1.12.2 and there is nothing like this mod for that version.  Just curious if it was ever thought of or discussed before or if its even possible.  Thanks!

**Comment by Ellpeck** [comment]
No.

**Comment by ThatCrazyDad** [comment]
Ok cool thx for the response :D
