### ISSUE TITLE
Filter Modules don't seem to be doing anything

### ISSUE THREAD

**Issue by leoddd** [Ellpeck/PrettyPipes#9]
So I've been trying to set up a simple sorting network for hours now.
At first I tried to use Retrieval Modules, but even the High Tier ones didn't let me filter by enough items, so I thought I'd switch over to Filter Moduels (which obviously allow far more items to be filtered by).
I replaced all of my Retrieval Modules with Filter Modules and then outfitted my source chest with a High Extractor, so it starts pumping its insides into the network for the items to be filtered.
However, for some reason, the Extractor only ever sends its items into one exact chest. If I disconnect that chest from the network, it stops outputting any items at all. The filter on that chest is disregarded entirely, it's set to only accept Dirt and Grass but the Extractor dumps Redstone, Quartz and Ore inside it happily.
I tried toggling around the Allow/Disallow settings on literally everything and have tried every possible combination of them, but the Extractor keeps being fixated on this singular chest to dump everything into. The whitelist on the Extractor does work, it will only throw out Obsidian when I tell it to, but I want it to dump out everything and leave the sorting to the Filters.

Is this not how the pipes are intended to work? If not, how ARE you supposed to do something like this? How do I get the Filter Modules to have any effect on the game at all? Right now no setting I give them affects gameplay at all, no matter where I put them, be it with an Extractor, a Retrieval module or all by themselves.

To make it clearer what I'm trying to do, here's a bad screenshot:
![aa](https://user-images.githubusercontent.com/20242421/81089265-6ffd5e80-8efc-11ea-9e77-1f1e060d19fa.png)

The chest on the left is my (temporary) source chest with the Extractor attached. It's set to disallow with no blocks selected (which I hope means it spews out everything).
All the receiving chests have a Filter Module attached set to Allow with a set of blocks on the whitelist (often they're High Filters that have been Populated with the chests' contents).
Regardless of all this, the Extractor will throw everything and the kitchen sink into that one chest at the top, three rows from the right. That chest of course also has a filter like all the other ones, I really don't know what's so special about it.

**Comment by Ellpeck** [comment]
Are your filters set to disallow or allow the filtered items? It sounds like you're disallowing all items you actually want to allow.

**Comment by Ellpeck** [comment]
I just did a very simple test on the newest version, and I can't reproduce this issue.
https://imgur.com/a/BmCLUp6
