### ISSUE TITLE
[feature] Search on item description

### ISSUE THREAD

**Issue by ianwijma** [Ellpeck/PrettyPipes#90]
I was curious if it would be possible to make item descriptions seachable. To make searching for a certain enchanted book easier.

![image](https://user-images.githubusercontent.com/17692119/125193157-6739b280-e28e-11eb-8d29-0fcb96e44655.png)

Example: 
![image](https://user-images.githubusercontent.com/17692119/125193099-175aeb80-e28e-11eb-8ddc-90d795353c5b.png)

**Comment by Brillik** [comment]
Is there any chance we can get this issue fixed in 1.16.5? I realize it's been fixed in 1.18 and 19, but as I'm working through E6E, it'd be very nice to have.
