### ISSUE TITLE
Camouflage/Façade description

### ISSUE THREAD

**Issue by AngleWyrm10** [Ellpeck/PrettyPipes#92]
An image on the SourceForge description appears to demonstrate a feature similar to facades:

![](https://raw.githubusercontent.com/Ellpeck/PrettyPipes/main/media/2020-10-17_00.58.03.png)

But there is no description of what it is. There is however at least one closed issue ( #70 ) mentioning camouflage.

This is a request to add at least one sentence to the sourceforge description page, conveying how to use that feature.

**Comment by Ellpeck** [comment]
The pipe wrench description explains how to add covers to pipes.

**Comment by AngleWyrm10** [comment]
The time and energy expended to reply to this issue with a sentence could have more profitably been spent on one descriptive sentence on the SourceForge description page and reached a larger audience.

**Comment by Ellpeck** [comment]
thanks for your aggressive input, but I still would have had to reply to this issue regardless.
